### ISSUE TITLE
Hello, through the USB line chrysanthemum chain, how to achieve? I only have PS3 handle, can you help me modify a PS3? thank you

### ISSUE THREAD

**Issue by skyaee** [ninoguba/ev3-robotic-arm#1]
Hello, through the USB line chrysanthemum chain, how to achieve? I only have PS3 handle, can you help me modify a PS3?
thank you

**Comment by ninoguba** [comment]
You can check out this project on ev3dev that uses the PS3 controller - https://www.ev3dev.org/projects/2016/03/10/Gamepad-Omnibot/

For USB daisy chaining, you can also check out the answer provided here - https://bricks.stackexchange.com/questions/8888/how-to-connect-two-lego-bricks-ev3-by-usb-using-python

**Comment by skyaee** [comment]
Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ninoguba/ev3-robotic-arm"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月14日(星期四) 上午7:00
收件人:&nbsp;"ninoguba/ev3-robotic-arm"<ev3-robotic-arm@noreply.github.com&gt;;
抄送:&nbsp;"471622426"<471622426@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ninoguba/ev3-robotic-arm] Hello, through the USB line chrysanthemum chain, how to achieve? I only have PS3 handle, can you help me modify a PS3? thank you (#1)





 
You can check out this project on ev3dev that uses the PS3 controller - https://www.ev3dev.org/projects/2016/03/10/Gamepad-Omnibot/
 
For USB daisy chaining, you can also check out the answer provided here - https://bricks.stackexchange.com/questions/8888/how-to-connect-two-lego-bricks-ev3-by-usb-using-python
